source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!

#pod 'MagicalRecord', :git => ‘https://github.com/magicalpanda/MagicalRecord.git’, :branch => ‘release/3.0'
#pod 'BNRCoreDataStack'
pod 'CoreStore'
pod 'GCDKit'